flags: {}
resolver: lts-12.26
extra-deps:
- fltkhs-0.8.0.1
- fltkhs-themes-0.2.0.1
- load-font-0.1.0.2
- asset-bundle-0.1.0.1
allow-newer: true
nix:
  packages:
    - autoconf
    - pkgconfig
    - xorg.libX11
    - xorg.libXft
