flags: {}
resolver: lts-15.0
extra-deps:
- fltkhs-0.8.0.3
- fltkhs-themes-0.2.0.2
- load-font-0.1.0.3
- asset-bundle-0.1.0.2
allow-newer: true
nix:
  packages:
    - autoconf
    - pkgconfig
    - xorg.libX11
    - xorg.libXft
